# Generated by Django 5.2.15 on 2026-07-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(default='Vox Regina Caeli', max_length=200)),
                ('descricao', models.TextField(blank=True, default='Revista digital católica independente')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('email_contato', models.EmailField(blank=True, default='', max_length=254)),
                ('instagram', models.URLField(blank=True, default='')),
                ('youtube', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('twitter_x', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
