# Generated by Django 6.0.1 on 2026-04-24 20:55

import blog.models.post_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_model.caminho_imagem_capa),
        ),
    ]
