# Generated by Django 5.2.15 on 2026-07-09 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacaoPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('visitante_hash', models.CharField(blank=True, default='', max_length=64)),
                ('referrer', models.URLField(blank=True, default='')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='publicacoes.publicacao')),
            ],
            options={
                'verbose_name': 'Visualização',
                'verbose_name_plural': 'Visualizações',
                'ordering': ['-data'],
            },
        ),
    ]
